### ISSUE TITLE
How to add standart components in a builder

### ISSUE THREAD

**Issue by zotona** [wizardpb/vaadin-builder#1]
Hi!
Very cool project. How can i  add some initialized component 

```
    setContent(
                builder.build {
                    panel(caption: 'Vaadin Builder Sampler') {
                    addComponent(someComp)
                    }
                }
        )
```

**Comment by wizardpb** [comment]
Hi, thanks for getting in touch, and glad you find it useful.

Right now, there is no direct way to do this. Since the build primitives will return the component they create, you can work around it with this:

builder.build {
    def container = panel(caption: ‘Vaadin Builder Sample’) {
    // Add whatever you want
    }
    container.addComponent(someComp)    // … or any other ‘add’ primitive that the container supports
    container                           // make sure the return value is correct
}

What we really want is another builder primitive that will just add the component, thus:

builder.build {
    panel(caption: ‘Vaadin Builder Sample’) {
    // Add whatever you want
    widget(someComponent)
    // Add others
    }
}

but this doesn’t exist yet. It’s not hard to add. Give me a week or two (I’m working on another project right now) and I can add it. I’m inclined to call it ‘widget’ after the SwingBuilder primitive that does the same thing, but I guess it could also be ‘addComponent’ as you show. Not sure if this will conflict with anything tho’

-pb

**Comment by wizardpb** [comment]
Actually, it turns out to be even easier. Seems it’s already done. I haven’t worked on this in months - it’s amazing what you can forget :-)

All the builder verbs can take a pre-built component as argument. So you can do

Label l = new Label(“Text”)

builder.build {
	panel(caption: ‘Vaadin Builder Sample’) {
		label(l)
	}
}

Just make sure that the verb and the component type match, otherwise the node will try and construct a new instance of that type using the value passed in. See lines 43 -45 in ComponentFactory

-pb

**Comment by zotona** [comment]
Thanks for the advanced answer Paul!
I have a small expirience at groovy. Please tell me, is it possible config IDEA, for code assist, when we write a bulder? i found solution its a custom gdsl script, like https://shyiko.wordpress.com/2010/12/15/gradle-through-groovydsl/

And its would great if you can implement Widget interface support!  i think more common usage is add complex(composite) UI at some level, not a vaadin primitivesm like you show
`Label l = new Label(“Text”) builder.build { panel(caption: ‘Vaadin Builder Sample’) { label(l) } }`

**Comment by wizardpb** [comment]
Actually, it turns out to be even easier. Seems it’s already done. I
haven’t worked on this in months - it’s amazing what you can forget :-)

All the builder verbs can take a pre-built component as argument. So you
can do

Label l = new Label(“Text”)

builder.build {

def container = panel(caption: ‘Vaadin Builder Sample’) {

label(l)
}

}

Just make sure that the verb and the component type match,otherwise the
node will try and construct a new instance of that type using the value
passed in. See lines 43 -45 in ComponentFactory

-pb

On Dec 13, 2015, at 6:39 AM, zotona notifications@github.com wrote:

Hi!
Very cool project How can i add some initialized component

```
setContent(
            builderbuild {
                panel(caption: 'Vaadin Builder Sampler') {
                addComponent(someComp)
                }
            }
    )
```

—
Reply to this email directly or view it on GitHub
https://github.com/wizardpb/vaadin-builder/issues/1.

**Comment by wizardpb** [comment]
The builder syntax is regular Groovy - it is nothing more than Groovy code,
and executes as such. If you have IDEA set up for Groovy, you will get
syntax and completion (as far as possible). The builder makes use of a lot
of Groovy's dynamic dispatch, so it's often not possible for an IDE to do
much completion, as it doesn't have the typing information required. But
IDEA will do as good a job as any.

As to a composite, the added component can easliybe a container with a
whole composite below it, This works just as well:

VerticalLayout l = new VerticalLayout()

// Add whatever you want

builder.build {

panel(caption: ‘Vaadin Builder Sample’) {

verticalLayout(l)
}

}
